name: url-collector

requires: 2.0.0
needs:
  - ssh
  - docker
  - git

repository: ssh://git@source.factorial.io:2222/shuber/url-collector.git


hosts:
  ci:
    needs:
      - local
    scripts:
      image:build:
        defaults:
          user: gitlab-ci-token
          tag: latest
        script:
        - docker build -t registry.factorial.io:8443/shuber/url-collector:%arguments.tag% .
        - docker login -u %arguments.user% -p %arguments.password% registry.factorial.io:8443
        - docker push registry.factorial.io:8443/shuber/url-collector:%arguments.tag%
