[package]
name = "url-collector"
version = "0.10.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.76"
async-recursion = "1.0.5"
clap = { version = "4.4.11", features = ["derive"] }
futures = "0.3.30"
indicatif = { version = "0.17.7", features = ["rayon"] }
rand = "0.8.5"
rayon = "1.8.0"
reqwest = { version = "0.11.23", features = ["blocking"] }
serde = { version = "1.0.193", features = ["derive"] }
serde_json = { version = "1.0.108", features = [] }
serde_yaml = "0.9.29"
simplelog = { version = "0.12.1", features = ["paris"] }
sitemap = "0.4.1"
tokio = { version = "1.35.1", features = ["macros", "rt-multi-thread"] }
url = { version = "2.5.0", features = ["serde"] }

[workspace.metadata.release]
sign-tag = true
pre-release-replacements = [
  {file="README.md", search="Current release: [a-z0-9\\.-]+", replace="Current release: {{version}}"} ,
  {file="CHANGELOG.md", search="Unreleased", replace="{{version}}", min=1},
  {file="CHANGELOG.md", search="\\.\\.\\.HEAD", replace="...{{tag_name}}", exactly=1},
  {file="CHANGELOG.md", search="ReleaseDate", replace="{{date}}", min=1},
  {file="CHANGELOG.md", search="<!-- next-header -->", replace="<!-- next-header -->\n## [Unreleased] - ReleaseDate\n", exactly=1},
  {file="CHANGELOG.md", search="<!-- next-url -->", replace="<!-- next-url -->\n[Unreleased]: https://github.com/stmh/url-collector/compare/{{tag_name}}...HEAD", exactly=1},
]
